### ISSUE TITLE
[Bug] Incorrect file paths

### ISSUE THREAD

**Issue by Silvia-Wachira** [creativecommons/reversionary-rights#27] opened 2024-10-03 11:15 UTC
## Description
The web page is only displaying the HTML but the CSS is not being rendered when you go live. This is because the file paths  do not point to where the files are located. 

## Reproduction

1. Fork and clone the repository
2. Install the project dependencies
3. Run the servers.
4. See error. No CSS is being rendered in the webpage

## Expectation
We expect to see a page with all the images, logos and styles.
## Screenshots

![Screenshot from 2024-10-02 20-38-41](https://github.com/user-attachments/assets/44386bdc-384a-456a-a8fd-4ea1fa0efe7a)

## Additional context
In order to work on the issue of the unresponsive header, this issue needs to be fixed first.

## Implementation
- [ x ] I would be interested in resolving this bug.

**Comment by possumbilities** [comment] 2024-10-03 14:46
Closing as a duplicate of #28

**Closed as completed by possumbilities** 2024-10-03 14:46 UTC
Labels: 🟧 priority: high, ⛔️ status: discarded, 🛠 goal: fix, 💻 aspect: code
